export const tracks = [
  {
    id: "dywtylm",
    artist: "Sleep Token",
    track: "DYWTYLM",
    year: 2023,
    genres: ["Pop", "Indie"],
  },
  {
    id: "electric",
    artist: "Leila K",
    track: "Electric",
    year: 1996,
    genres: ["Pop", "Electronic", "Dance"],
  },
  {
    id: "sirius",
    artist: "Alan Parsons Project",
    track: "Sirius",
    year: 1982,
    genres: ["Pop", "Instrumental"],
  },
  {
    id: "truecolours",
    artist: "Kite",
    track: "True Colours",
    year: 2015,
    genres: ["Synthpop", "Dark Electronic"],
  },
  {
    id: "blindinglights",
    artist: "The Weeknd",
    track: "Blinding Lights",
    year: 2020,
    genres: ["Pop", "Synthwave"],
  },
  {
    id: "dancingonmyown",
    artist: "Robyn",
    track: "Dancing on My Own",
    year: 2010,
    genres: ["Pop", "Dance"],
  },
  {
    id: "ismyloveenough",
    artist: "White Lies",
    track: "Is My Love Enough?",
    year: 2016,
    genres: ["Pop", "Dance"],
  },
  {
    id: "festen",
    artist: "Teddybears",
    track: "Festen",
    year: 2010,
    genres: ["Pop", "Instrumental", "Electronic"],
  },
  {
    id: "ificould",
    artist: "Jack Johnson",
    track: "If I Could",
    year: 2005,
    genres: ["Acoustic", "Folk"],
  },
  {
    id: "goldeneye",
    artist: "Grant Kirkhope",
    track: "GoldenEye 64 Pause Music",
    year: 1997,
    genres: ["Video Game", "Instrumental"],
  },
  {
    id: "whatislove",
    artist: "Haddaway",
    track: "What is Love",
    year: 1993,
    genres: ["Pop", "Dance"],
  },
  {
    id: "alleyesonme",
    artist: "Bo Burnham",
    track: "All Eyes on Me",
    year: 2021,
    genres: ["Pop", "Dark Comedy"],
  },
  {
    id: "gerudovalley",
    artist: "Koji Kondo",
    track: "Gerudo Valley (The Legend of Zelda: Ocarina of Time)",
    year: 1998,
    genres: ["Instrumental", "Video Game"],
  },
  {
    id: "terrastheme",
    artist: "Nobuo Uematsu",
    track: "Terra's Theme (Final Fantasy VI)",
    year: 1994,
    genres: ["Instrumental", "Video Game"],
  },
  {
    id: "nightcall",
    artist: "Kavinsky",
    track: "Nightcall",
    year: 2010,
    genres: ["Synth-Pop", "Electronic"],
  },
  {
    id: "children",
    artist: "Robert Miles",
    track: "Children",
    year: 1995,
    genres: ["Trance", "Instrumental"],
  },
  {
    id: "somethingaboutus",
    artist: "Daft Punk",
    track: "Something About Us",
    year: 2001,
    genres: ["Pop", "Electronic"],
  },
];
